# GitHub Copilot environment customization
# This file customizes the ephemeral development environment for GitHub Copilot coding agent
# Documentation: https://docs.github.com/en/copilot/customizing-copilot/customizing-the-development-environment-for-copilot-coding-agent

setup:
  # Install UV (Python package manager)
  - name: Install UV
    run: |
      curl -LsSf https://astral.sh/uv/install.sh | sh
      export PATH="$HOME/.cargo/bin:$PATH"
      uv --version

  # Install GitHub MCP server
  - name: Install GitHub MCP server
    run: |
      npm install -g @github/github-mcp-server
      github-mcp-server --version || echo "GitHub MCP server installed"