# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
        contents: read
    name: Test ${{ matrix.os }} Python ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python_version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    env:
      UV_SYSTEM_PYTHON: 1
    steps:
        - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        - name: Setup python
          uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
          with:
            python-version: ${{ matrix.python_version }}
            architecture: x64
        - name: Install uv
          uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

        # dependencies are in uv.lock
        - name: Install dependencies
          run: |
            uv sync --all-extras --locked

        - name: Lint with ruff
          run: uv run ruff check .
        - name: Check types with mypy
          run: uv run mypy src/iparq --config-file=pyproject.toml
        - name: Check types with ty
          run: uv run ty check
        - name: Check formatting with ruff
          run: uv run ruff format --check .
        - name: Run Python tests with coverage
          run: uv run pytest -vv --cov=src/iparq --cov-report=xml --cov-report=term-missing
        
        - name: Upload coverage to Codecov
          if: runner.os != 'Windows'
          uses: codecov/codecov-action@e53489f4d376d79066609109e7a95a29eb3740b1 # v7.0.0
          with:
            files: ./coverage.xml
            fail_ci_if_error: false
            verbose: true
          env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
